# Generated by Django 4.2.7 on 2023-11-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=150)),
                ('address', models.TextField(max_length=250)),
                ('cost', models.CharField(max_length=50)),
                ('celebration', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
