# Generated by Django 4.2.7 on 2023-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('AR', 'Art'), ('CH', 'Charity'), ('CM', 'Comedy Show'), ('CN', 'Conference'), ('CO', 'Concert'), ('CS', 'Class / Seminar'), ('EX', 'Exercise / Fitness'), ('FA', 'Fashion'), ('FE', 'Festival'), ('FI', 'Film'), ('FO', 'Food'), ('GA', 'Gala'), ('MU', 'Music'), ('NE', 'Networking'), ('OT', 'Other'), ('PA', 'Party'), ('SP', 'Sports'), ('TH', 'Theater'), ('WE', 'Wedding'), ('WR', 'Work Outing')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(),
        ),
    ]
