# Generated by Django 4.2.7 on 2023-11-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_event_category_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='celebration',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
