# Generated by Django 4.2.7 on 2023-11-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_event_options_alter_event_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='$0.00', max_digits=8),
        ),
    ]
