# Generated by Django 4.2.7 on 2023-11-03 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('AR', 'Art'), ('CH', 'Charity'), ('CM', 'Comedy Show'), ('CN', 'Conference'), ('CO', 'Concert'), ('CS', 'Class / Seminar'), ('EX', 'Exercise / Fitness'), ('FA', 'Fashion'), ('FE', 'Festival'), ('FI', 'Film'), ('FO', 'Food'), ('FU', 'Fundraiser'), ('GA', 'Gala'), ('MU', 'Music'), ('NE', 'Networking'), ('OT', 'Other'), ('PA', 'Party'), ('SP', 'Sports'), ('TH', 'Theater'), ('WE', 'Wedding'), ('WR', 'Work Outing')], default=0, max_length=2),
        ),
    ]
